import type { EnterpriseApiEndpoint, EnterpriseEvent } from './types';

export const enterpriseSeedEvent: EnterpriseEvent = {
  id: 'sx-enterprise-2026',
  slug: 'spendx-enterprise-summit-2026',
  name: 'SpendX Enterprise Summit',
  tagline: 'The AI-native operating system for modern events',
  description:
    'A production-shaped event experience covering registration, ticketing, agenda planning, indoor navigation, networking, AI concierge orchestration, seat management, and post-event follow-up.',
  category: 'Technology',
  type: 'summit',
  mode: 'hybrid',
  status: 'draft',
  startDate: '2026-04-12T09:00:00.000Z',
  endDate: '2026-04-13T18:00:00.000Z',
  location: 'Landmark Centre, Lagos',
  bannerImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1600&q=80',
  venueDescription:
    'Ground floor entrance with keynote hall to the north, workshop rooms on the east wing, sponsor boulevard through the center, and amenities near the south concourse.',
  attendeeCount: 842,
  ticketTiers: [
    {
      id: 'ticket-free',
      name: 'Explorer',
      type: 'free',
      price: 0,
      currency: 'USD',
      capacity: 400,
      sold: 312,
      benefits: ['Event access', 'AI concierge', 'Community links'],
      customFields: ['Company', 'Role'],
    },
    {
      id: 'ticket-pro',
      name: 'Operator',
      type: 'paid',
      price: 49,
      currency: 'USD',
      capacity: 300,
      sold: 241,
      benefits: ['All sessions', 'Priority seating', 'Certificate'],
      customFields: ['Dietary preference', 'LinkedIn URL'],
    },
    {
      id: 'ticket-vip',
      name: 'VIP Command',
      type: 'vip',
      price: 129,
      currency: 'USD',
      capacity: 120,
      sold: 77,
      benefits: ['Lounge access', 'Speaker breakfast', 'Fast track check-in'],
      customFields: ['Assistant name', 'VIP access notes'],
    },
  ],
  sessions: [
    {
      id: 'session-1',
      title: 'Keynote: Event Ops That Never Break',
      description: 'Reliability patterns for live events with offline-first fallback and AI guardrails.',
      type: 'keynote',
      roomId: 'node-hall-a',
      roomName: 'Keynote Hall',
      speakerIds: ['speaker-1'],
      start: '2026-04-12T09:30:00.000Z',
      end: '2026-04-12T10:20:00.000Z',
      capacity: 500,
      attendees: 418,
      live: true,
      waitlistCount: 12,
      trackId: 'track-main',
    },
    {
      id: 'session-2',
      title: 'Workshop: AI Concierge Design',
      description: 'How to build FAQ retrieval, escalation paths, and manual override into the attendee experience.',
      type: 'workshop',
      roomId: 'node-room-b',
      roomName: 'Studio B',
      speakerIds: ['speaker-2'],
      start: '2026-04-12T11:00:00.000Z',
      end: '2026-04-12T12:00:00.000Z',
      capacity: 180,
      attendees: 146,
      live: false,
      waitlistCount: 9,
      trackId: 'track-ai',
    },
    {
      id: 'session-3',
      title: 'Panel: Indoor Maps From Plain English',
      description: 'A practical conversation on structured venue models, occupancy overlays, and attendee wayfinding.',
      type: 'panel',
      roomId: 'node-room-c',
      roomName: 'Workshop Room C',
      speakerIds: ['speaker-1', 'speaker-3'],
      start: '2026-04-12T13:30:00.000Z',
      end: '2026-04-12T14:15:00.000Z',
      capacity: 220,
      attendees: 173,
      live: false,
      waitlistCount: 5,
      trackId: 'track-maps',
    },
    {
      id: 'session-4',
      title: 'Networking Mixer',
      description: 'Opt-in networking with community links, smart matching, and sponsor intros.',
      type: 'networking',
      roomId: 'node-booth-hub',
      roomName: 'Sponsor Boulevard',
      speakerIds: [],
      start: '2026-04-12T16:00:00.000Z',
      end: '2026-04-12T17:00:00.000Z',
      capacity: 350,
      attendees: 121,
      live: false,
      waitlistCount: 0,
      trackId: 'track-community',
    },
  ],
  speakers: [
    {
      id: 'speaker-1',
      name: 'Amara Okafor',
      role: 'Founder',
      company: 'SpendX',
      bio: 'Amara leads SpendX and focuses on operational systems that stay graceful under event-time pressure.',
      image: 'https://api.dicebear.com/9.x/notionists/svg?seed=Amara',
      socialLinks: [
        { label: 'LinkedIn', url: 'https://linkedin.com' },
        { label: 'X', url: 'https://x.com' },
      ],
    },
    {
      id: 'speaker-2',
      name: 'David Chen',
      role: 'AI Product Lead',
      company: 'Open Events Lab',
      bio: 'David designs AI assistants that help organizers without taking control away from them.',
      image: 'https://api.dicebear.com/9.x/notionists/svg?seed=David',
      socialLinks: [{ label: 'Website', url: 'https://example.com' }],
    },
    {
      id: 'speaker-3',
      name: 'Chioma Adebayo',
      role: 'Venue Systems Architect',
      company: 'Atlas Rooms',
      bio: 'Chioma works on indoor navigation and occupancy-aware venue experiences.',
      image: 'https://api.dicebear.com/9.x/notionists/svg?seed=Chioma',
      socialLinks: [{ label: 'LinkedIn', url: 'https://linkedin.com' }],
    },
  ],
  sponsors: [
    {
      id: 'sponsor-1',
      name: 'Cloudflare',
      tier: 'Platinum',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Cloudflare_Logo.png',
      blurb: 'Edge delivery and reliability tooling for live digital experiences.',
      boothId: 'node-booth-1',
      leadsCaptured: 88,
    },
    {
      id: 'sponsor-2',
      name: 'Supabase',
      tier: 'Gold',
      logo: 'https://seeklogo.com/images/S/supabase-logo-DCC676FFE2-seeklogo.com.png',
      blurb: 'Database, auth, and realtime primitives for modern apps.',
      boothId: 'node-booth-2',
      leadsCaptured: 61,
    },
  ],
  communityLinks: [
    { id: 'community-1', label: 'WhatsApp Ops Circle', platform: 'whatsapp', url: 'https://whatsapp.com' },
    { id: 'community-2', label: 'Discord Backstage', platform: 'discord', url: 'https://discord.com' },
    { id: 'community-3', label: 'Slack Partner Lounge', platform: 'slack', url: 'https://slack.com' },
  ],
  attendees: [
    {
      id: 'attendee-1',
      name: 'Femi Ade',
      company: 'Orbit Labs',
      role: 'Community Lead',
      avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Femi',
      bio: 'Looking for collaboration on attendee retention and event-led growth.',
      networkingState: 'discoverable',
      community: 'WhatsApp',
    },
    {
      id: 'attendee-2',
      name: 'Mia Johnson',
      company: 'Signal House',
      role: 'Operations Manager',
      avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Mia',
      bio: 'Interested in offline-first check-in flows and staffing models.',
      networkingState: 'pending',
      community: 'Discord',
    },
    {
      id: 'attendee-3',
      name: 'Tolu Balogun',
      company: 'Meridian',
      role: 'Product Designer',
      avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Tolu',
      bio: 'Exploring mobile-first conference layouts and map interactions.',
      networkingState: 'connected',
      community: 'Slack',
    },
  ],
  venueNodes: [
    { id: 'node-entry', name: 'Main Entrance', kind: 'entrance', x: 10, y: 82, occupancy: 28, description: 'Primary attendee arrival point and badge collection.' },
    { id: 'node-hall-a', name: 'Keynote Hall', kind: 'room', x: 38, y: 28, occupancy: 84, description: 'Main stage for keynote and featured sessions.' },
    { id: 'node-room-b', name: 'Studio B', kind: 'room', x: 72, y: 24, occupancy: 61, description: 'Hands-on workshop room with flexible seating.' },
    { id: 'node-room-c', name: 'Workshop Room C', kind: 'room', x: 76, y: 50, occupancy: 46, description: 'Mid-size panel room near sponsor boulevard.' },
    { id: 'node-booth-hub', name: 'Sponsor Boulevard', kind: 'booth', x: 48, y: 56, occupancy: 54, description: 'Sponsor zone with lead capture and demos.' },
    { id: 'node-booth-1', name: 'Cloudflare Booth', kind: 'booth', x: 40, y: 62, occupancy: 39, description: 'Reliability demos and swag pickup.' },
    { id: 'node-booth-2', name: 'Supabase Booth', kind: 'booth', x: 58, y: 62, occupancy: 44, description: 'Database and auth product clinic.' },
    { id: 'node-restroom', name: 'Amenities', kind: 'amenity', x: 18, y: 44, occupancy: 21, description: 'Restrooms, water refill, and accessibility support.' },
  ],
  venueRoutes: [
    { id: 'route-1', fromNodeId: 'node-entry', toNodeId: 'node-hall-a', label: 'Fastest route to keynote', durationMinutes: 3 },
    { id: 'route-2', fromNodeId: 'node-hall-a', toNodeId: 'node-room-b', label: 'Move to Studio B', durationMinutes: 4 },
    { id: 'route-3', fromNodeId: 'node-room-b', toNodeId: 'node-booth-hub', label: 'Walk to sponsor boulevard', durationMinutes: 2 },
  ],
  conciergeFaqs: [
    {
      id: 'faq-1',
      question: 'Where is the keynote hall?',
      answer: 'The keynote hall is north of the main entrance. Use the Venue Map tab and select Keynote Hall for the fastest route.',
      tags: ['map', 'keynote', 'directions'],
    },
    {
      id: 'faq-2',
      question: 'How do I check in to a session?',
      answer: 'Open your Ticket Wallet or session card, tap Check In, and we will queue the action if your network is unstable.',
      tags: ['checkin', 'ticket', 'offline'],
    },
    {
      id: 'faq-3',
      question: 'What community groups can I join?',
      answer: 'You can join the event WhatsApp, Discord, and Slack spaces from the Networking and Community sections.',
      tags: ['community', 'networking'],
    },
    {
      id: 'faq-4',
      question: 'What is next on my schedule?',
      answer: 'Your next saved session appears at the top of My Agenda with a countdown and room guidance.',
      tags: ['agenda', 'next session'],
    },
  ],
  dashboardMetrics: [
    { id: 'metric-1', label: 'Registrations', value: '842', trend: '+12% this week' },
    { id: 'metric-2', label: 'Revenue', value: '$18.2k', trend: '+8 VIP today' },
    { id: 'metric-3', label: 'Check-ins', value: '519', trend: '41 queued offline' },
    { id: 'metric-4', label: 'Engagement', value: '74%', trend: 'Q&A and polls rising' },
  ],
  team: [
    {
      id: 'team-1',
      name: 'Amara Okafor',
      role: 'organizer',
      permissions: ['events:write', 'announcements:send', 'seats:assign', 'ai:action'],
      note: 'Owns event setup, approvals, and live orchestration.',
    },
    {
      id: 'team-2',
      name: 'Kemi Ojo',
      role: 'moderator',
      permissions: ['qna:moderate', 'polls:manage', 'attendees:view'],
      note: 'Monitors attendee issues and escalates unusual patterns.',
    },
    {
      id: 'team-3',
      name: 'Leo Martins',
      role: 'speaker_manager',
      permissions: ['speakers:write', 'sessions:view', 'announcements:view'],
      note: 'Coordinates speakers and communicates program changes.',
    },
    {
      id: 'team-4',
      name: 'Hana Yusuf',
      role: 'sponsor_manager',
      permissions: ['sponsors:write', 'leads:view'],
      note: 'Handles sponsor ops, lead capture, and booth updates.',
    },
  ],
  seatAssignments: [
    { id: 'seat-1', sessionId: 'session-1', label: 'Keynote Hall - Main Floor', total: 500, allocated: 418, available: 82 },
    { id: 'seat-2', sessionId: 'session-2', label: 'Studio B - Workshop Block', total: 180, allocated: 146, available: 34 },
    { id: 'seat-3', sessionId: 'session-3', label: 'Workshop Room C - Panel Layout', total: 220, allocated: 173, available: 47 },
  ],
  waitlist: [
    { id: 'wait-1', sessionId: 'session-1', attendeeId: 'attendee-4', attendeeName: 'Rita Mensah', priority: 'VIP priority', status: 'waiting' },
    { id: 'wait-2', sessionId: 'session-2', attendeeId: 'attendee-5', attendeeName: 'Noah Reed', priority: 'Timestamp order', status: 'waiting' },
    { id: 'wait-3', sessionId: 'session-3', attendeeId: 'attendee-6', attendeeName: 'Ife Thomas', priority: 'Speaker overlap match', status: 'promoted' },
  ],
  announcements: [
    {
      id: 'announce-1',
      title: 'Doors open at 8:30 AM',
      message: 'Badge collection begins at the main entrance. QR wallet passes are ready.',
      audience: 'attendees',
      createdAt: '2026-04-11T15:00:00.000Z',
      status: 'sent',
    },
    {
      id: 'announce-2',
      title: 'Workshop seating adjustment',
      message: 'Studio B capacity has been expanded and waitlist promotions are in progress.',
      audience: 'all',
      createdAt: '2026-04-12T08:20:00.000Z',
      status: 'scheduled',
    },
  ],
  polls: [
    {
      id: 'poll-1',
      sessionId: 'session-1',
      question: 'Which operating principle matters most for live events?',
      options: [
        { id: 'poll-1-opt-1', label: 'Offline-first core loop', votes: 62 },
        { id: 'poll-1-opt-2', label: 'Manual override paths', votes: 38 },
        { id: 'poll-1-opt-3', label: 'AI-assisted support', votes: 57 },
      ],
    },
    {
      id: 'poll-2',
      sessionId: 'session-2',
      question: 'Which concierge surface do you want most?',
      options: [
        { id: 'poll-2-opt-1', label: 'Voice directions', votes: 21 },
        { id: 'poll-2-opt-2', label: 'Ticket help', votes: 18 },
        { id: 'poll-2-opt-3', label: 'Schedule suggestions', votes: 29 },
      ],
    },
  ],
  notifications: [
    {
      id: 'notification-1',
      type: 'schedule',
      title: 'Session reminder',
      message: 'Your keynote starts in 20 minutes. Follow the route from the main entrance.',
      target: 'agenda',
      read: false,
      createdAt: '2026-04-12T09:10:00.000Z',
    },
    {
      id: 'notification-2',
      type: 'announcement',
      title: 'Capacity updated',
      message: 'Waitlisted attendees are being promoted for Studio B right now.',
      target: 'ticket',
      read: true,
      createdAt: '2026-04-12T10:05:00.000Z',
    },
  ],
  transportEstimate: {
    originLabel: 'Victoria Island, Lagos',
    distanceKm: 11.8,
    durationMinutes: 28,
    estimatedCost: 6500,
    currency: 'NGN',
    countdownLabel: '24 days to event start',
  },
  analytics: {
    revenue: '$18.2k',
    registrations: '842',
    attendance: '519 live check-ins',
    engagement: '74% active participation',
    polls: '225 poll votes',
    qna: '94 moderated questions',
    checkins: '41 queued offline syncs',
    waitlistFillRate: '63% promoted',
  },
  certificates: [
    { id: 'cert-1', title: 'Enterprise Summit Attendance', issuedOn: '2026-04-14' },
    { id: 'cert-2', title: 'AI Concierge Workshop Completion', issuedOn: '2026-04-14' },
  ],
  pastEvents: [
    {
      id: 'past-1',
      title: 'SpendX Cities Meetup',
      date: '2025-11-20',
      summary: 'You attended networking and budget planning sessions and connected with 4 attendees.',
    },
    {
      id: 'past-2',
      title: 'Ops Reliability Forum',
      date: '2025-07-09',
      summary: 'Your AI-assisted schedule included 3 workshops and one post-event certificate download.',
    },
  ],
};

export const enterpriseApiSpec: EnterpriseApiEndpoint[] = [
  { method: 'POST', path: '/auth/register', handler: 'onSignUpSubmit', surface: 'shared', summary: 'Register attendee, host, moderator, or speaker roles.' },
  { method: 'POST', path: '/auth/login', handler: 'onSignInSubmit', surface: 'shared', summary: 'Authenticate and return role-aware session state.' },
  { method: 'GET', path: '/events/:eventId', handler: 'onDashboardLoad', surface: 'shared', summary: 'Load event details with sessions, tickets, map, and AI state.' },
  { method: 'POST', path: '/events', handler: 'onEventCreate', surface: 'host', summary: 'Create a new event draft with banner, venue, and lifecycle settings.' },
  { method: 'PATCH', path: '/events/:eventId', handler: 'onEventEdit', surface: 'host', summary: 'Update event details, ticketing, or publishing state.' },
  { method: 'POST', path: '/events/:eventId/sessions', handler: 'onSessionAdd', surface: 'host', summary: 'Create or reorder program sessions across tracks.' },
  { method: 'POST', path: '/events/:eventId/speakers', handler: 'onSpeakerAdd', surface: 'host', summary: 'Create speakers and attach them to sessions.' },
  { method: 'POST', path: '/events/:eventId/tickets', handler: 'onTicketSetup', surface: 'host', summary: 'Configure ticket tiers, pricing, and registration fields.' },
  { method: 'POST', path: '/events/:eventId/seats', handler: 'onSeatAssign', surface: 'host', summary: 'Assign and rebalance seat blocks for active sessions.' },
  { method: 'PATCH', path: '/events/:eventId/waitlist/:attendeeId/promote', handler: 'onWaitlistPromote', surface: 'host', summary: 'Promote attendees from waitlist into newly available capacity.' },
  { method: 'POST', path: '/events/:eventId/announcements', handler: 'onAnnouncementSend', surface: 'host', summary: 'Broadcast push, email, and in-app updates.' },
  { method: 'POST', path: '/ai/action', handler: 'onHostAIAction', surface: 'host', summary: 'Execute organizer AI commands for schedules, maps, and notifications.' },
  { method: 'POST', path: '/payments/checkout', handler: 'onTicketPurchase', surface: 'attendee', summary: 'Initiate Whop checkout for the selected ticket tier.' },
  { method: 'POST', path: '/events/:eventId/transport', handler: 'onTransportEstimate', surface: 'attendee', summary: 'Calculate travel cost, duration, and countdown for the attendee.' },
  { method: 'POST', path: '/attendees/:attendeeId/agenda', handler: 'onAgendaUpdate', surface: 'attendee', summary: 'Create or update the attendee personal agenda.' },
  { method: 'POST', path: '/events/:eventId/checkin', handler: 'onCheckIn', surface: 'attendee', summary: 'Validate QR entry and session attendance.' },
  { method: 'POST', path: '/events/:eventId/connect', handler: 'onConnectRequest', surface: 'attendee', summary: 'Send attendee networking requests and mutual contact flows.' },
  { method: 'POST', path: '/events/:eventId/polls/:pollId/vote', handler: 'onPollVote', surface: 'attendee', summary: 'Submit a live engagement vote.' },
  { method: 'POST', path: '/events/:eventId/feedback', handler: 'onFeedbackSubmit', surface: 'attendee', summary: 'Collect post-event ratings and surveys.' },
  { method: 'GET', path: '/attendees/:attendeeId/history', handler: 'onHistoryLoad', surface: 'attendee', summary: 'Retrieve past events, certificates, and post-event recommendations.' },
];
